workflows:
  ios-release:
    name: iOS Release

    integrations:
      app_store_connect: PMSalesQuote

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.premmotors.salesquote

    scripts:
      - flutter pub get
      - find . -name "Podfile" -execdir pod install \;
      - xcode-project use-profiles
      - name: Build IPA
  script: |
    flutter build ipa --release --export-method app-store --build-name=1.0.0 --build-number=$PROJECT_BUILD_NUMBER

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
