workflows:
  ios-release:
    name: iOS Release

    integrations:
      app_store_connect: PMSalesQuote
      
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.premmotors.salesquote

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      # Crucial for Windows Users: Removes automated local signing requirements
      - name: Set Manual Code Signing
        script: |
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
